import Head from "next/head";
import Image from "next/image";
import LoginButton from "../components/login-button";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>OnTarget v1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"bg-white"}>
        <h2>OnTarget</h2>
        <p>this is home page</p>
        <LoginButton />
      </main>
    </>
  );
}
